version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spark:
    image: bitnami/spark:latest
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
    volumes:
      - ./scripts:/app/scripts
      - ./data:/app/data

  airflow:
#    image: apache/airflow
    build:
      context: .
      dockerfile: Dockerfile  # Assuming you have a Dockerfile
    container_name: airflow
    depends_on:
      - spark
      - postgres
    ports:
      - "8081:8080"
    environment:
      - LOAD_EX=y
      - EXECUTOR=Local
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - FERNET_KEY=kxQJJuFjsfTcmvSHnfbjkqB94qU7NsjVx8rOpB5F8Fo=
#      - PYTHONPATH=/app:/usr/local/lib/python3.7/site-packages:$PYTHONPATH  # Set PYTHONPATH

#      - PYTHONPATH=/app:$PYTHONPATH

    volumes:
      - ./airflow/dags:/app/airflow/dags
      - ./scripts:/app/scripts
      - ./data:/app/data
      - ./config/airflow.cfg:/opt/bitnami/airflow/airflow.cfg
    command: ["airflow", "webserver"]  # Correct command format
    #command: ["airflow", "scheduler"]


volumes:
  postgres_data:
