version: '3'

services:
  spark:
    image: bitnami/spark:latest
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
    volumes:
      - ./scripts:/app/scripts
      - ./data:/app/data

  airflow:
    image: puckel/docker-airflow
    container_name: airflow
    depends_on:
      - spark
    ports:
      - "8081:8080"
    environment:
      - LOAD_EX=y
      - EXECUTOR=LocalExecutor
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./scripts:/app/scripts
      - ./data:/app/data
    command: webserver
