version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spark:
    image: bitnami/spark:latest
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
    volumes:
      - ./scripts:/app/scripts
      - ./data:/app/data

  airflow:
    image: puckel/docker-airflow
    container_name: airflow
    depends_on:
      - spark
      - postgres
    ports:
      - "8081:8080"
    environment:
      - LOAD_EX=y
      - EXECUTOR=Local
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow

    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./scripts:/app/scripts
      - ./data:/app/data
      - ./config/airflow.cfg:/opt/bitnami/airflow/airflow.cfg

    command: webserver

volumes:
  postgres_data:
